name: 🦅🚀🔥 Deploy 🔥🚀🦅
on:
  push:
    branches:
      - main
jobs:
  buildAssets:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: ndihpezembo build files
          path: ./public/build
      - name: Upload Build to FTP SERVER Ndihpezembo
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 'ndihpezembo.online'
          username: 'u573755972.ndihpezembo'
          password: 'Au573755972@2024'
          local-dir: ./public/build/
          server-dir: ./build/
